site_name: Documentation Mille Nuits
theme:
  name: material
  logo: assets/images/logo.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
nav:
  - Accueil: index.md
  - SP1 - Gestion de l'infrastructure réseau:
    - Mission 1 - Définission d'un nouveau plan d'adressage: sp1mission1.md
    - Mission 2 - Mise en place de l'infrastructure réseau: sp1mission2.md
    - Mission 3 - Mise en place de l'infrastructure réseau avec VLAN visiteurs et dans le VLAN commerciaux: sp1mission3.md
  - SP2 - Gestion du parc informatique:
    - Mission 1 - Créer une documentation avec MkDocs et GitHub Pages: sp2mission1.md
    - Mission 4 - Recherche et mise en place d’un outil de gestion d’incident: sp2mission4.md
  - SP3 - Gestion des services principaux AD - DHCP:
    - Mission 1 - Mise en place du serveur Windows Server 2019: sp3mission1.md
    - Mission 2 - Mise en place du serveur DHCP sous Linux: sp3mission2.md
    - Mission 3 - Mise en place d’un serveur NAS avec authentification Active Directory et redirection de dossiers MN07: sp3mission3.md
